import { useState, useMemo, useCallback, memo } from "react";
import { m } from "framer-motion";
import "./EmojiPicker.css";
import "flag-icons/css/flag-icons.min.css";

// Country flag mapping for flag-icons
const flagMapping = {
  "🇺🇸": "fi fi-us",
  "🇬🇧": "fi fi-gb",
  "🇨🇦": "fi fi-ca",
  "🇦🇺": "fi fi-au",
  "🇩🇪": "fi fi-de",
  "🇫🇷": "fi fi-fr",
  "🇮🇹": "fi fi-it",
  "🇯🇵": "fi fi-jp",
  "🇰🇷": "fi fi-kr",
  "🇨🇳": "fi fi-cn",
  "🇮🇳": "fi fi-in",
  "🇧🇷": "fi fi-br",
  "🇷🇺": "fi fi-ru",
  "🇪🇸": "fi fi-es",
  "🇳🇱": "fi fi-nl",
  "🇧🇪": "fi fi-be",
  "🇨🇭": "fi fi-ch",
  "🇦🇹": "fi fi-at",
  "🇸🇪": "fi fi-se",
  "🇳🇴": "fi fi-no",
  "🇩🇰": "fi fi-dk",
  "🇫🇮": "fi fi-fi",
  "🇵🇱": "fi fi-pl",
  "🇨🇿": "fi fi-cz",
  "🇭🇺": "fi fi-hu",
  "🇵🇹": "fi fi-pt",
  "🇬🇷": "fi fi-gr",
  "🇹🇷": "fi fi-tr",
  "🇲🇽": "fi fi-mx",
  "🇦🇷": "fi fi-ar",
  "🇨🇴": "fi fi-co",
  "🇨🇱": "fi fi-cl",
  "🇵🇪": "fi fi-pe",
  "🇻🇪": "fi fi-ve",
  "🇪🇨": "fi fi-ec",
  "🇺🇾": "fi fi-uy",
  "🇵🇾": "fi fi-py",
  "🇧🇴": "fi fi-bo",
  "🇸🇻": "fi fi-sv",
  "🇬🇹": "fi fi-gt",
  "🇭🇳": "fi fi-hn",
  "🇳🇮": "fi fi-ni",
  "🇨🇷": "fi fi-cr",
  "🇵🇦": "fi fi-pa",
  "🇩🇴": "fi fi-do",
  "🇯🇲": "fi fi-jm",
  "🇭🇹": "fi fi-ht",
  "🇨🇺": "fi fi-cu",
  "🇵🇷": "fi fi-pr",
  "🇧🇧": "fi fi-bb",
  "🇹🇹": "fi fi-tt",
  "🇬🇾": "fi fi-gy",
  "🇸🇷": "fi fi-sr",
  "🇦🇼": "fi fi-aw",
  "🇧🇶": "fi fi-bq",
  "🇨🇼": "fi fi-cw",
  "🇸🇽": "fi fi-sx",
  "🇧🇱": "fi fi-bl",
  "🇬🇫": "fi fi-gf",
  "🇬🇵": "fi fi-gp",
  "🇲🇶": "fi fi-mq",
  "🇾🇹": "fi fi-yt",
  "🇷🇪": "fi fi-re",
  "🇵🇫": "fi fi-pf",
  "🇳🇨": "fi fi-nc",
  "🇼🇫": "fi fi-wf",
  "🇵🇲": "fi fi-pm",
  "🇬🇱": "fi fi-gl",
  "🇫🇴": "fi fi-fo",
  "🇦🇽": "fi fi-ax",
  "🇮🇸": "fi fi-is",
  "🇮🇪": "fi fi-ie",
  "🇱🇺": "fi fi-lu",
  "🇲🇨": "fi fi-mc",
  "🇱🇮": "fi fi-li",
  "🇦🇩": "fi fi-ad",
  "🇸🇲": "fi fi-sm",
  "🇻🇦": "fi fi-va",
  "🇲🇹": "fi fi-mt",
  "🇨🇾": "fi fi-cy",
  "🇧🇬": "fi fi-bg",
  "🇷🇴": "fi fi-ro",
  "🇭🇷": "fi fi-hr",
  "🇸🇮": "fi fi-si",
  "🇲🇪": "fi fi-me",
  "🇷🇸": "fi fi-rs",
  "🇲🇰": "fi fi-mk",
  "🇦🇱": "fi fi-al",
  "🇽🇰": "fi fi-xk",
  "🇧🇦": "fi fi-ba",
  "🇲🇩": "fi fi-md",
  "🇪🇪": "fi fi-ee",
  "🇱🇻": "fi fi-lv",
  "🇱🇹": "fi fi-lt",
  "🇧🇾": "fi fi-by",
  "🇺🇦": "fi fi-ua",
  "🇬🇪": "fi fi-ge",
  "🇦🇲": "fi fi-am",
  "🇦🇿": "fi fi-az",
  "🇰🇿": "fi fi-kz",
  "🇰🇬": "fi fi-kg",
  "🇹🇯": "fi fi-tj",
  "🇹🇲": "fi fi-tm",
  "🇺🇿": "fi fi-uz",
  "🇲🇳": "fi fi-mn",
  "🇰🇵": "fi fi-kp",
  "🇹🇼": "fi fi-tw",
  "🇭🇰": "fi fi-hk",
  "🇲🇴": "fi fi-mo",
  "🇯🇴": "fi fi-jo",
  "🇱🇧": "fi fi-lb",
  "🇸🇾": "fi fi-sy",
  "🇮🇶": "fi fi-iq",
  "🇰🇼": "fi fi-kw",
  "🇸🇦": "fi fi-sa",
  "🇧🇭": "fi fi-bh",
  "🇶🇦": "fi fi-qa",
  "🇦🇪": "fi fi-ae",
  "🇴🇲": "fi fi-om",
  "🇾🇪": "fi fi-ye",
  "🇮🇱": "fi fi-il",
  "🇵🇸": "fi fi-ps",
  "🇪🇬": "fi fi-eg",
  "🇱🇾": "fi fi-ly",
  "🇩🇿": "fi fi-dz",
  "🇲🇦": "fi fi-ma",
  "🇹🇳": "fi fi-tn",
  "🇪🇭": "fi fi-eh",
  "🇲🇷": "fi fi-mr",
  "🇲🇱": "fi fi-ml",
  "🇸🇳": "fi fi-sn",
  "🇬🇲": "fi fi-gm",
  "🇬🇳": "fi fi-gn",
  "🇸🇱": "fi fi-sl",
  "🇱🇷": "fi fi-lr",
  "🇨🇮": "fi fi-ci",
  "🇧🇫": "fi fi-bf",
  "🇹🇬": "fi fi-tg",
  "🇧🇯": "fi fi-bj",
  "🇳🇪": "fi fi-ne",
  "🇳🇬": "fi fi-ng",
  "🇹🇩": "fi fi-td",
  "🇨🇲": "fi fi-cm",
  "🇨🇫": "fi fi-cf",
  "🇬🇦": "fi fi-ga",
  "🇨🇬": "fi fi-cg",
  "🇦🇴": "fi fi-ao",
  "🇬🇶": "fi fi-gq",
  "🇸🇹": "fi fi-st",
  "🇨🇻": "fi fi-cv",
  "🇬🇼": "fi fi-gw",
  "🇧🇮": "fi fi-bi",
  "🇷🇼": "fi fi-rw",
  "🇹🇿": "fi fi-tz",
  "🇰🇪": "fi fi-ke",
  "🇺🇬": "fi fi-ug",
  "🇸🇴": "fi fi-so",
  "🇩🇯": "fi fi-dj",
  "🇪🇹": "fi fi-et",
  "🇪🇷": "fi fi-er",
  "🇸🇸": "fi fi-ss",
  "🇸🇩": "fi fi-sd",
  "🇿🇦": "fi fi-za",
  "🇧🇼": "fi fi-bw",
  "🇿🇲": "fi fi-zm",
  "🇿🇼": "fi fi-zw",
  "🇲🇼": "fi fi-mw",
  "🇲🇿": "fi fi-mz",
  "🇸🇿": "fi fi-sz",
  "🇱🇸": "fi fi-ls",
  "🇳🇦": "fi fi-na",
  "🇲🇬": "fi fi-mg",
  "🇲🇺": "fi fi-mu",
  "🇸🇨": "fi fi-sc",
  "🇹🇴": "fi fi-to",
  "🇼🇸": "fi fi-ws",
  "🇸🇧": "fi fi-sb",
  "🇻🇺": "fi fi-vu",
  "🇳🇷": "fi fi-nr",
  "🇹🇻": "fi fi-tv",
  "🇰🇮": "fi fi-ki",
  "🇲🇭": "fi fi-mh",
  "🇵🇼": "fi fi-pw",
  "🇫🇲": "fi fi-fm",
  "🇲🇵": "fi fi-mp",
  "🇬🇺": "fi fi-gu",
  "🇦🇸": "fi fi-as",
  "🇻🇮": "fi fi-vi",
  "🇺🇲": "fi fi-um",
  "🇲🇸": "fi fi-ms",
  "🇹🇨": "fi fi-tc",
  "🇻🇬": "fi fi-vg",
  "🇧🇲": "fi fi-bm",
  "🇰🇾": "fi fi-ky",
  "🇦🇮": "fi fi-ai",
  "🇫🇰": "fi fi-fk",
  "🇬🇸": "fi fi-gs",
  "🇸🇭": "fi fi-sh",
  "🇮🇴": "fi fi-io",
  "🇵🇳": "fi fi-pn",
  "🇨🇽": "fi fi-cx",
  "🇨🇨": "fi fi-cc",
  "🇳🇫": "fi fi-nf",
  "🇦🇶": "fi fi-aq",
  "🇧🇻": "fi fi-bv",
  "🇭🇲": "fi fi-hm",
  "🇹🇫": "fi fi-tf"
};

const emojis = [
  // Faces & Emotions (100+ emojis)
  "😀", "😃", "😄", "😁", "😆", "😅", "🤣", "😂", "🙂", "🙃", "😉", "😊", "😇", "🥰", "😍", "🤩", "😘", "😗", "☺️", "😚", "😙", "🥲", "😋", "😛", "😜", "🤪", "😝", "🤑", "🤗", "🤭", "🤫", "🤔", "🤐", "🤨", "😐", "😑", "😶", "🙄", "😏", "😒", "🙁", "☹️", "😔", "😪", "😴", "😷", "🤒", "🤕", "🤢", "🤮", "🤧", "🥵", "🥶", "🥴", "😵‍💫", "🤯", "🤠", "🥳", "🥸", "😎", "🤓", "🧐", "😕", "😟", "😮", "😯", "😲", "😳", "😦", "😧", "😨", "😰", "😥", "😢", "😭", "😱", "😖", "😣", "😞", "😓", "😩", "😫", "🥱", "😤", "😡", "😠", "🤬", "😈", "👿", "💀", "☠️", "👻", "👽", "🤖", "😺", "😸", "😹", "😻", "😼", "😽", "🙀", "😿", "😾", "🙈", "🙉", "🙊",

  // Gestures & People (21+ emojis)
  "👋", "🤚", "🖐️", "✋", "🖖", "👌", "🤌", "🤏", "✌️", "🤞", "🤟", "🤘", "🤙", "👈", "👉", "👆", "🖕", "👇", "☝️", "👍", "🙏",

  // Hearts & Love (15+ emojis)
  "❤️", "🧡", "💛", "💚", "💙", "💜", "🖤", "🤍", "🤎", "💔", "❤️‍🔥", "❤️‍🩹", "❣️", "💕", "💞",

  // Nature & Animals (20+ emojis)
  "🐶", "🐱", "🐭", "🐹", "🐰", "🦊", "🐻", "🐼", "🐨", "🐯", "🦁", "🐮", "🐷", "🐽", "🐸", "🐵", "🙈", "🙉", "🙊", "🐒",

  // Food & Drinks (100+ emojis)
  "🍎", "🍊", "🍋", "🍌", "🍉", "🍇", "🍓", "🫐", "🍈", "🍒", "🍑", "🥭", "🍍", "🥥", "🥝", "🍅", "🍆", "🥑", "🥒", "🥬", "🥦", "🧄", "🧅", "🥕", "🌽", "🌶️", "🫑", "🍄", "🥜", "🌰", "🍠", "🥔",
  "🥚", "🍳", "🥓", "🥩", "🍗", "🍖", "🐔", "🐟", "🐠", "🐡", "🦀", "🦞", "🦐", "🦑", "🦪", "🐙", "🐚",
  "🧀", "🥛", "🍼",
  "🍞", "🥖", "🥨", "🥯", "🥐", "🥞", "🧇",
  "🍕", "🍔", "🍟", "🌭", "🍿", "🥟", "🥠", "🥡", "🍱", "🍘", "🍙", "🍚", "🍛", "🍜", "🍝", "🍢", "🍣", "🍤", "🍥", "🥮", "🥧", "🍦", "🍨", "🍩", "🍪", "🎂", "🍰", "🧁", "🍫", "🍬", "🍭", "🍮", "🍯",
  "☕", "🫖", "🍵", "🧃", "🥤", "🧋", "🍶", "🍺", "🍻", "🥂", "🍷", "🥃", "🍸", "🍹", "🧉", "🍾",
  "🥄", "🍴", "🍽️",
  "🥙", "🌯", "🥗", "🥘", "🫕", "🥫", "🍲",

  // Activities & Sports (15+ emojis)
  "⚽", "🏀", "🏈", "⚾", "🥎", "🎾", "🏐", "🏉", "🥏", "🎱", "🪀", "🏓", "🏸", "🏒", "🏑",

  // Travel & Places (15+ emojis)
  "🚗", "🚕", "🚙", "🚌", "🚎", "🏎️", "🚓", "🚑", "🚒", "🚐", "🚚", "🚛", "🚜", "🏍️", "🛵",

  // Objects & Symbols (20+ emojis)
  "🔥", "💧", "🌊", "⭐", "✨", "💫", "🌟", "🌠", "🎇", "🎆", "🎈", "🎉", "🎊", "🎂", "🎁", "🎀", "🎗️", "🎟️", "🎫", "🎖️",

  // Weather & Nature (10+ emojis)
  "☀️", "🌤️", "⛅", "☁️", "🌧️", "⛈️", "🌩️", "❄️", "🌨️", "🌈",

  // Technology & Devices (10+ emojis)
  "📱", "📲", "☎️", "📞", "📟", "📠", "📺", "📻", "🎙️", "🎚️",

  // Flags & Symbols (200+ emojis)
  "🏁", "🚩", "🎌", "🏴", "🏳️", "🏳️‍🌈", "🏳️‍⚧️", "🏴‍☠️",
  "🇺🇸", "🇬🇧", "🇨🇦", "🇦🇺", "🇩🇪", "🇫🇷", "🇮🇹", "🇯🇵", "🇰🇷", "🇨🇳", "🇮🇳", "🇧🇷",
  "🇷🇺", "🇪🇸", "🇳🇱", "🇧🇪", "🇨🇭", "🇦🇹", "🇸🇪", "🇳🇴", "🇩🇰", "🇫🇮", "🇵🇱", "🇨🇿", "🇭🇺", "🇵🇹", "🇬🇷", "🇹🇷",
  "🇲🇽", "🇦🇷", "🇨🇴", "🇨🇱", "🇵🇪", "🇻🇪", "🇪🇨", "🇺🇾", "🇵🇾", "🇧🇴", "🇸🇻", "🇬🇹", "🇭🇳", "🇳🇮", "🇨🇷", "🇵🇦",
  "🇩🇴", "🇯🇲", "🇭🇹", "🇨🇺", "🇵🇷", "🇧🇧", "🇹🇹", "🇬🇾", "🇸🇷", "🇦🇼", "🇧🇶", "🇨🇼", "🇸🇽", "🇧🇱", "🇬🇫", "🇬🇵",
  "🇲🇶", "🇾🇹", "🇷🇪", "🇵🇫", "🇳🇨", "🇼🇫", "🇵🇲", "🇬🇱", "🇫🇴", "🇦🇽", "🇮🇸", "🇮🇪", "🇱🇺", "🇲🇨", "🇱🇮", "🇦🇩",
  "🇸🇲", "🇻🇦", "🇲🇹", "🇨🇾", "🇧🇬", "🇷🇴", "🇭🇷", "🇸🇮", "🇲🇪", "🇷🇸", "🇲🇰", "🇦🇱", "🇽🇰", "🇧🇦", "🇲🇩", "🇪🇪",
  "🇱🇻", "🇱🇹", "🇧🇾", "🇺🇦", "🇬🇪", "🇦🇲", "🇦🇿", "🇰🇿", "🇰🇬", "🇹🇯", "🇹🇲", "🇺🇿", "🇲🇳", "🇰🇵", "🇹🇼", "🇭🇰",
  "🇲🇴", "🇯🇴", "🇱🇧", "🇸🇾", "🇮🇶", "🇰🇼", "🇸🇦", "🇧🇭", "🇶🇦", "🇦🇪", "🇴🇲", "🇾🇪", "🇮🇱", "🇵🇸", "🇪🇬", "🇱🇾",
  "🇩🇿", "🇲🇦", "🇹🇳", "🇪🇭", "🇲🇷", "🇲🇱", "🇸🇳", "🇬🇲", "🇬🇳", "🇸🇱", "🇱🇷", "🇨🇮", "🇧🇫", "🇹🇬", "🇧🇯", "🇳🇪",
  "🇳🇬", "🇹🇩", "🇨🇲", "🇨🇫", "🇬🇦", "🇨🇬", "🇦🇴", "🇬🇶", "🇸🇹", "🇨🇻", "🇬🇼", "🇧🇮", "🇷🇼", "🇹🇿", "🇰🇪", "🇺🇬",
  "🇸🇴", "🇩🇯", "🇪🇹", "🇪🇷", "🇸🇸", "🇸🇩", "🇿🇦", "🇧🇼", "🇿🇲", "🇿🇼", "🇲🇼", "🇲🇿", "🇸🇿", "🇱🇸", "🇳🇦", "🇲🇬",
  "🇲🇺", "🇸🇨", "🇹🇴", "🇼🇸", "🇸🇧", "🇻🇺", "🇳🇷", "🇹🇻", "🇰🇮", "🇲🇭", "🇵🇼", "🇫🇲", "🇲🇵", "🇬🇺", "🇦🇸", "🇻🇮",
  "🇺🇲", "🇲🇸", "🇹🇨", "🇻🇬", "🇧🇲", "🇰🇾", "🇦🇮", "🇫🇰", "🇬🇸", "🇸🇭", "🇮🇴", "🇵🇳", "🇨🇽", "🇨🇨", "🇳🇫", "🇦🇶",
  "🇧🇻", "🇭🇲", "🇹🇫"
];

export default function EmojiPicker({ onEmojiSelect, isOpen, onClose }) {
  const [selectedCategory, setSelectedCategory] = useState("all");
  const [searchQuery, setSearchQuery] = useState("");

  const handleEmojiClick = useCallback((emoji) => {
    onEmojiSelect(emoji);
    onClose();
  }, [onEmojiSelect, onClose]);

  const handleSearchChange = useCallback((e) => {
    setSearchQuery(e.target.value);
  }, []);

  // Emoji name mappings for better search
  const emojiNames = {
    "😀": "smile grinning face happy joy",
    "😂": "joy face tears laugh happy joy lol",
    "😊": "blush smile happy joy",
    "😍": "heart eyes love affection",
    "🥰": "smiling face with hearts love affection",
    "😘": "kiss blowing kiss love affection",
    "😉": "wink playful",
    "😎": "cool sunglasses confident",
    "🤔": "thinking hmm confused",
    "😮": "surprised wow shocked",
    "😢": "cry sad tears upset",
    "😭": "sob cry loud sad upset",
    "😤": "angry mad frustrated",
    "😡": "rage angry furious",
    "🥺": "pleading puppy eyes sad",
    "😴": "sleep sleepy tired",
    "🤯": "exploding head mind blown shocked",
    "🥴": "woozy drunk dizzy confused",
    "😵": "dizzy stars confused",
    "🤐": "zipper mouth silent quiet",
    "😋": "yum delicious tasty hungry",
    "😜": "tongue wink crazy playful",
    "🤪": "zany crazy silly",
    "😝": "tongue squint crazy playful",
    "🤑": "money mouth rich greedy",
    "🤗": "hug hugging affectionate",
    "🤭": "hand mouth giggle shy",
    "🤫": "shush quiet silent",
    "🤥": "lie lying dishonest",
    "😶": "no mouth silent speechless",
    "👍": "thumbs up good yes",
    "🇬🇪": "georgia flag country georgian tbilisi caucasus",
    "👎": "thumbs down bad no",
    "👌": "ok perfect",
    "✌️": "peace victory",
    "🤞": "fingers crossed luck",
    "👏": "clap applause",
    "🙌": "raised hands praise",
    "🤝": "handshake deal",
    "🙏": "pray please",
    "💪": "muscle strong",
    "👋": "wave hello",
    "🤚": "raised back hand",
    "🖐️": "hand splayed",
    "✋": "raised hand stop",
    "🖖": "vulcan salute spock",
    "🤏": "pinching hand small",
    "🤟": "love you gesture hand",
    "🤘": "rock on devil horns",
    "🤙": "call me hand phone",
    "👈": "point left backhand",
    "👉": "point right backhand",
    "👆": "point up backhand",
    "🖕": "middle finger rude",
    "👇": "point down backhand",
    "☝️": "index pointing up",
    "❤️": "heart love red",
    "💙": "blue heart",
    "💜": "purple heart",
    "💛": "yellow heart",
    "💚": "green heart",
    "🤍": "white heart",
    "🖤": "black heart",
    "🤎": "brown heart",
    "💔": "broken heart",
    "❣️": "heart exclamation",
    "💕": "two hearts",
    "💞": "revolving hearts",
    "💓": "beating heart",
    "💗": "growing heart",
    "💖": "sparkling heart",
    "🐶": "dog puppy",
    "🐱": "cat kitten",
    "🐭": "mouse",
    "🐹": "hamster",
    "🐰": "rabbit bunny",
    "🦊": "fox",
    "🐻": "bear",
    "🐼": "panda",
    "🐨": "koala",
    "🐯": "tiger",
    "🦁": "lion",
    "🐮": "cow",
    "🐷": "pig",
    "🐸": "frog",
    "🐵": "monkey",
    "🍕": "pizza",
    "🍔": "burger hamburger",
    "🍟": "fries french fries",
    "🌭": "hot dog",
    "🍿": "popcorn",
    "🍩": "donut",
    "🍪": "cookie",
    "🧁": "cupcake",
    "🍰": "cake",
    "☕": "coffee",
    "🍺": "beer",
    "🍻": "beers cheers",
    "🥂": "champagne cheers",
    "🍷": "wine",
    "🥃": "whiskey",
    "🍸": "cocktail",
    "🍹": "tropical drink",
    "🧉": "mate",
    "🍾": "champagne bottle",
    "🥤": "milk glass",
    "🍎": "apple red fruit",
    "🍊": "orange fruit citrus",
    "🍋": "lemon fruit citrus",
    "🍌": "banana fruit yellow",
    "🍉": "watermelon fruit",
    "🍇": "grapes fruit purple",
    "🍓": "strawberry fruit red",
    "🫐": "blueberries fruit blue",
    "🍈": "melon fruit",
    "🍒": "cherries fruit red",
    "🍑": "peach fruit",
    "🥭": "mango fruit tropical",
    "🍍": "pineapple fruit tropical",
    "🥥": "coconut fruit tropical",
    "🥝": "kiwi fruit green",
    "🍅": "tomato fruit red vegetable",
    "🍆": "eggplant vegetable purple",
    "🥑": "avocado fruit green",
    "🥦": "broccoli vegetable green",
    "🥬": "lettuce vegetable green leafy",
    "⚽": "soccer football",
    "🏀": "basketball",
    "🏈": "football american",
    "⚾": "baseball",
    "🎾": "tennis",
    "🏐": "volleyball",
    "🏉": "rugby",
    "🎱": "pool billiards",
    "🏓": "ping pong table tennis",
    "🏸": "badminton",
    "🥅": "goal net",
    "🏒": "hockey",
    "🏑": "field hockey",
    "🏏": "cricket",
    "⛳": "golf flag",
    "🚗": "car automobile",
    "🚕": "taxi",
    "🚙": "suv",
    "🚌": "bus",
    "🚎": "trolleybus",
    "🏎️": "racing car",
    "🚓": "police car",
    "🚑": "ambulance",
    "🚒": "fire truck",
    "🚐": "minibus",
    "🚚": "truck",
    "🚛": "articulated lorry",
    "🚜": "tractor",
    "🏍️": "motorcycle",
    "✈️": "airplane plane",
    "🛵": "motor scooter",
    "🚲": "bicycle bike",
    "🛴": "kick scooter",
    "🛹": "skateboard",
    "🚁": "helicopter",
    "🚟": "suspension railway",
    "🚠": "mountain cableway",
    "🚡": "aerial tramway",
    "🛤️": "railway track",
    "🛣️": "motorway",
    "🗺️": "world map",
    "⛽": "fuel pump gas",
    "🚨": "police car light siren",
    "🚥": "traffic light horizontal",
    "🚦": "traffic light vertical",
    "🛑": "stop sign",
    "🚧": "construction",
    "⚓": "anchor",
    "⛵": "sailboat",
    "🛶": "canoe",
    "🚤": "speedboat",
    "🛳️": "passenger ship",
    "⛴️": "ferry",
    "🛥️": "motor boat",
    "🚢": "ship",
    "🛩️": "small airplane",
    "🛫": "airplane departure",
    "🛬": "airplane arrival",
    "🪂": "parachute",
    "💺": "seat",
    "🚀": "rocket",
    "🛸": "flying saucer ufo",
    "🚞": "mountain railway",
    "🚝": "monorail",
    "🚄": "high speed train",
    "🚅": "bullet train",
    "🚈": "light rail",
    "🚂": "locomotive",
    "🚊": "tram",
    "🚉": "station",
    "🚇": "metro subway",
    "🏗️": "building construction",
    "🏭": "factory",
    "🏢": "office building",
    "🏬": "department store",
    "🏣": "post office",
    "🏤": "post office european",
    "🏥": "hospital",
    "🏦": "bank",
    "🏨": "hotel",
    "🏪": "convenience store",
    "🏫": "school",
    "🏩": "love hotel",
    "💒": "wedding chapel",
    "🏛️": "classical building",
    "⛪": "church",
    "🕌": "mosque",
    "🕍": "synagogue",
    "⛩️": "shinto shrine",
    "🕋": "kaaba",
    "⛲": "fountain",
    "⛺": "tent",
    "🌁": "foggy",
    "🌃": "night with stars",
    "🏙️": "cityscape",
    "🌄": "sunrise over mountains",
    "🌅": "sunrise",
    "🌆": "city at dusk",
    "🌇": "sunset",
    "🌉": "bridge at night",
    "♨️": "hot springs",
    "🎠": "carousel horse",
    "🎡": "ferris wheel",
    "🎢": "roller coaster",
    "💈": "barber pole",
    "🎪": "circus tent",
    "🔥": "fire flame",
    "💧": "droplet water",
    "🌊": "water wave",
    "⭐": "star",
    "✨": "sparkles",
    "💫": "dizzy",
    "🌟": "glowing star",
    "🌠": "shooting star",
    "🎇": "sparkler",
    "🎆": "fireworks",
    "🎈": "balloon",
    "🎉": "party popper",
    "🎊": "confetti ball",
    "🎂": "birthday cake",
    "🎁": "wrapped gift",
    "🎀": "ribbon",
    "🎗️": "reminder ribbon",
    "🎟️": "admission tickets",
    "🎫": "ticket",
    "🎖️": "military medal",
    "🏆": "trophy",
    "🏅": "sports medal",
    "🥇": "gold medal",
    "🥈": "silver medal",
    "🥉": "bronze medal",
    "🥎": "softball",
    "🥏": "flying disc",
    "🪀": "yo yo",
    "🥍": "lacrosse",
    "🪃": "boomerang",
    "🪁": "kite",
    "🏹": "bow and arrow",
    "🎣": "fishing pole",
    "🤿": "diving mask",
    "🥊": "boxing glove",
    "🥋": "martial arts uniform",
    "🎽": "running shirt",
    "🛷": "sled",
    "⛸️": "ice skate",
    "🥌": "curling stone",
    "🎿": "skis",
    "⛷️": "skier",
    "🏂": "snowboarder",
    "🏋️": "weight lifter",
    "🤸": "person cartwheeling gymnastics flip exercise",
    "⛹️": "person bouncing ball basketball dribble sport",
    "🤺": "person fencing sword fight sport",
    "🤾": "person playing handball throw catch sport",
    "🏌️": "person golfing golf club swing sport",
    "🧘": "person in lotus position yoga meditate relax",
    "🏃": "person running jog sprint exercise",
    "🚶": "person walking stroll hike exercise",
    "🧎": "person kneeling pray kneel down",
    "🧍": "person standing wait stand up",
    "🤸‍♀️": "woman cartwheeling",
    "🤸‍♂️": "man cartwheeling",
    "🤼": "people wrestling",
    "🤽": "person playing water polo",
    "🤾‍♀️": "woman playing handball",
    "🤾‍♂️": "man playing handball",
    "⛹️‍♀️": "woman bouncing ball",
    "⛹️‍♂️": "man bouncing ball",
    "🏌️‍♀️": "woman golfing",
    "🏌️‍♂️": "man golfing",
    "🏋️‍♀️": "woman lifting weights",
    "🏋️‍♂️": "man lifting weights",
    "🎭": "performing arts",
    "🎨": "artist palette",
    "🎬": "clapper board",
    "🎤": "microphone",
    "🎧": "headphone",
    "🎼": "musical score",
    "🎹": "musical keyboard",
    "🥁": "drum",
    "🪘": "long drum",
    "🎷": "saxophone",
    "🎺": "trumpet",
    "🪗": "accordion",
    "🎸": "guitar",
    "🪕": "banjo",
    "🎻": "violin",
    "🎲": "game die",
    "♠️": "spade suit",
    "♥️": "heart suit",
    "♦️": "diamond suit",
    "♣️": "club suit",
    "🃏": "joker",
    "🀄": "mahjong red dragon",
    "🎴": "flower playing cards",
    "🎯": "bullseye dart",
    "🎳": "bowling",
    "🎮": "video game",
    "🕹️": "joystick",
    "🎰": "slot machine",
    "☀️": "sun sunny",
    "🌤️": "sun behind small cloud",
    "⛅": "sun behind cloud",
    "☁️": "cloud",
    "🌧️": "cloud with rain",
    "⛈️": "cloud with lightning",
    "🌩️": "cloud with lightning",
    "❄️": "snowflake",
    "🌨️": "cloud with snow",
    "🌈": "rainbow",
    "🌂": "closed umbrella",
    "☂️": "umbrella",
    "⛱️": "umbrella on ground",
    "🌫️": "fog",
    "🌪️": "tornado",
    "🌬️": "wind face",
    "🌀": "cyclone",
    "🌥️": "sun behind large cloud",
    "🌦️": "sun behind rain cloud",
    "🌡️": "thermometer",
    "🏁": "chequered flag racing finish",
    "🚩": "triangular flag",
    "🎌": "crossed flags japan",
    "🏴": "black flag",
    "🏳️": "white flag",
    "🏳️‍🌈": "rainbow flag pride lgbt",
    "🏳️‍⚧️": "transgender flag",
    "🏴‍☠️": "pirate flag skull crossbones",
    "🇺🇸": "united states america usa flag",
    "🇬🇧": "united kingdom great britain uk flag",
    "🇨🇦": "canada flag",
    "🇦🇺": "australia flag",
    "🇩🇪": "germany flag",
    "🇫🇷": "france flag",
    "🇮🇹": "italy flag",
    "🇯🇵": "japan flag",
    "🇰🇷": "south korea flag",
    "🇨🇳": "china flag",
    "🇮🇳": "india flag",
    "🇧🇷": "brazil flag",
    "🇷🇺": "russia flag",
    "🇪🇸": "spain flag",
    "🇳🇱": "netherlands flag",
    "🇧🇪": "belgium flag",
    "🇨🇭": "switzerland flag",
    "🇦🇹": "austria flag",
    "🇸🇪": "sweden flag",
    "🇳🇴": "norway flag",
    "🇩🇰": "denmark flag",
    "🇫🇮": "finland flag",
    "🇵🇱": "poland flag",
    "🇨🇿": "czech republic flag",
    "🇭🇺": "hungary flag",
    "🇵🇹": "portugal flag",
    "🇬🇷": "greece flag",
    "🇹🇷": "turkey flag",
    "🇲🇽": "mexico flag",
    "🇦🇷": "argentina flag",
    "🇨🇴": "colombia flag",
    "🇨🇱": "chile flag",
    "🇵🇪": "peru flag",
    "🇻🇪": "venezuela flag",
    "🇪🇨": "ecuador flag",
    "🇺🇾": "uruguay flag",
    "🇵🇾": "paraguay flag",
    "🇧🇴": "bolivia flag",
    "🇸🇻": "el salvador flag",
    "🇬🇹": "guatemala flag",
    "🇭🇳": "honduras flag",
    "🇳🇮": "nicaragua flag",
    "🇨🇷": "costa rica flag",
    "🇵🇦": "panama flag",
    "🇩🇴": "dominican republic flag",
    "🇯🇲": "jamaica flag",
    "🇭🇹": "haiti flag",
    "🇨🇺": "cuba flag",
    "🇵🇷": "puerto rico flag",
    "🇧🇧": "barbados flag",
    "🇹🇹": "trinidad tobago flag",
    "🇬🇾": "guyana flag",
    "🇸🇷": "suriname flag",
    "🇦🇼": "aruba flag",
    "🇧🇶": "caribbean netherlands flag",
    "🇨🇼": "curacao flag",
    "🇸🇽": "sint maarten flag",
    "🇧🇱": "saint barthelemy flag",
    "🇬🇫": "french guiana flag",
    "🇬🇵": "guadeloupe flag",
    "🇲🇶": "martinique flag",
    "🇾🇹": "mayotte flag",
    "🇷🇪": "reunion flag",
    "🇵🇫": "french polynesia flag",
    "🇳🇨": "new caledonia flag",
    "🇼🇫": "wallis futuna flag",
    "🇵🇲": "saint pierre miquelon flag",
    "🇬🇱": "greenland flag",
    "🇫🇴": "faroe islands flag",
    "🇦🇽": "aland islands flag",
    "🇮🇸": "iceland flag",
    "🇮🇪": "ireland flag",
    "🇱🇺": "luxembourg flag",
    "🇲🇨": "monaco flag",
    "🇱🇮": "liechtenstein flag",
    "🇦🇩": "andorra flag",
    "🇸🇲": "san marino flag",
    "🇻🇦": "vatican city flag",
    "🇲🇹": "malta flag",
    "🇨🇾": "cyprus flag",
    "🇧🇬": "bulgaria flag",
    "🇷🇴": "romania flag",
    "🇭🇷": "croatia flag",
    "🇸🇮": "slovenia flag",
    "🇲🇪": "montenegro flag",
    "🇷🇸": "serbia flag",
    "🇲🇰": "north macedonia flag",
    "🇦🇱": "albania flag",
    "🇽🇰": "kosovo flag",
    "🇧🇦": "bosnia herzegovina flag",
    "🇲🇩": "moldova flag",
    "🇪🇪": "estonia flag",
    "🇱🇻": "latvia flag",
    "🇱🇹": "lithuania flag",
    "🇧🇾": "belarus flag",
    "🇺🇦": "ukraine flag",
    "🇦🇲": "armenia flag",
    "🇦🇿": "azerbaijan flag",
    "🇰🇿": "kazakhstan flag",
    "🇰🇬": "kyrgyzstan flag",
    "🇹🇯": "tajikistan flag",
    "🇹🇲": "turkmenistan flag",
    "🇺🇿": "uzbekistan flag",
    "🇲🇳": "mongolia flag",
    "🇰🇵": "north korea flag",
    "🇹🇼": "taiwan flag",
    "🇭🇰": "hong kong flag",
    "🇲🇴": "macau flag",
    "🇯🇴": "jordan flag",
    "🇱🇧": "lebanon flag",
    "🇸🇾": "syria flag",
    "🇮🇶": "iraq flag",
    "🇰🇼": "kuwait flag",
    "🇸🇦": "saudi arabia flag",
    "🇧🇭": "bahrain flag",
    "🇶🇦": "qatar flag",
    "🇦🇪": "united arab emirates flag",
    "🇴🇲": "oman flag",
    "🇾🇪": "yemen flag",
    "🇮🇱": "israel flag",
    "🇵🇸": "palestine flag",
    "🇪🇬": "egypt flag",
    "🇱🇾": "libya flag",
    "🇩🇿": "algeria flag",
    "🇲🇦": "morocco flag",
    "🇹🇳": "tunisia flag",
    "🇪🇭": "western sahara flag",
    "🇲🇷": "mauritania flag",
    "🇲🇱": "mali flag",
    "🇸🇳": "senegal flag",
    "🇬🇲": "gambia flag",
    "🇬🇳": "guinea flag",
    "🇸🇱": "sierra leone flag",
    "🇱🇷": "liberia flag",
    "🇨🇮": "ivory coast flag",
    "🇧🇫": "burkina faso flag",
    "🇹🇬": "togo flag",
    "🇧🇯": "benin flag",
    "🇳🇪": "niger flag",
    "🇳🇬": "nigeria flag",
    "🇹🇩": "chad flag",
    "🇨🇲": "cameroon flag",
    "🇨🇫": "central african republic flag",
    "🇬🇦": "gabon flag",
    "🇨🇬": "congo flag",
    "🇦🇴": "angola flag",
    "🇬🇶": "equatorial guinea flag",
    "🇸🇹": "sao tome principe flag",
    "🇨🇻": "cape verde flag",
    "🇬🇼": "guinea bissau flag",
    "🇧🇮": "burundi flag",
    "🇷🇼": "rwanda flag",
    "🇹🇿": "tanzania flag",
    "🇰🇪": "kenya flag",
    "🇺🇬": "uganda flag",
    "🇸🇴": "somalia flag",
    "🇩🇯": "djibouti flag",
    "🇪🇹": "ethiopia flag",
    "🇪🇷": "eritrea flag",
    "🇸🇸": "south sudan flag",
    "🇸🇩": "sudan flag",
    "🇿🇦": "south africa flag",
    "🇧🇼": "botswana flag",
    "🇿🇲": "zambia flag",
    "🇿🇼": "zimbabwe flag",
    "🇲🇼": "malawi flag",
    "🇲🇿": "mozambique flag",
    "🇸🇿": "eswatini flag",
    "🇱🇸": "lesotho flag",
    "🇳🇦": "namibia flag",
    "🇲🇬": "madagascar flag",
    "🇲🇺": "mauritius flag",
    "🇸🇨": "seychelles flag",
    "🇹🇴": "tonga flag",
    "🇼🇸": "samoa flag",
    "🇸🇧": "solomon islands flag",
    "🇻🇺": "vanuatu flag",
    "🇳🇷": "nauru flag",
    "🇹🇻": "tuvalu flag",
    "🇰🇮": "kiribati flag",
    "🇲🇭": "marshall islands flag",
    "🇵🇼": "palau flag",
    "🇫🇲": "micronesia flag",
    "🇲🇵": "northern mariana islands flag",
    "🇬🇺": "guam flag",
    "🇦🇸": "american samoa flag",
    "🇻🇮": "us virgin islands flag",
    "🇺🇲": "us minor outlying islands flag",
    "🇲🇸": "montserrat flag",
    "🇹🇨": "turks caicos islands flag",
    "🇻🇬": "british virgin islands flag",
    "🇧🇲": "bermuda flag",
    "🇰🇾": "cayman islands flag",
    "🇦🇮": "anguilla flag",
    "🇫🇰": "falkland islands flag",
    "🇬🇸": "south georgia south sandwich islands flag",
    "🇸🇭": "saint helena flag",
    "🇮🇴": "british indian ocean territory flag",
    "🇵🇳": "pitcairn islands flag",
    "🥒": "cucumber vegetable",
    "🧄": "garlic vegetable",
    "🧅": "onion vegetable",
    "🥕": "carrot vegetable orange",
    "🌽": "corn vegetable maize",
    "🌶️": "pepper hot spicy vegetable",
    "🫑": "bell pepper vegetable",
    "🍄": "mushroom vegetable fungus",
    "🥜": "peanuts nuts legume",
    "🌰": "chestnut nut",
    "🍠": "sweet potato vegetable",
    "🥔": "potato vegetable",
    "🥚": "egg protein breakfast",
    "🍳": "cooking egg breakfast",
    "🥓": "bacon pork breakfast",
    "🥩": "steak meat beef",
    "🍗": "chicken leg poultry",
    "🍖": "meat bone protein",
    "🐔": "chicken poultry",
    "🐟": "fish seafood",
    "🐠": "tropical fish aquarium",
    "🐡": "blowfish puffer fish",
    "🦀": "crab seafood",
    "🦞": "lobster seafood",
    "🦐": "shrimp seafood",
    "🦑": "squid seafood",
    "🦪": "oyster seafood",
    "🐙": "octopus seafood",
    "🐚": "shell seafood",
    "🧀": "cheese dairy",
    "🥛": "milk dairy",
    "🍼": "baby bottle milk",
    "🍞": "bread baked",
    "🥖": "baguette bread french",
    "🥨": "pretzel bread german",
    "🥯": "bagel bread",
    "🥐": "croissant bread pastry",
    "🥞": "pancake breakfast",
    "🧇": "waffle breakfast",
    "🥟": "dumpling chinese",
    "🥠": "fortune cookie chinese",
    "🥡": "takeout box chinese",
    "🍱": "bento box japanese",
    "🍘": "rice cracker japanese",
    "🍙": "rice ball onigiri japanese",
    "🍚": "cooked rice japanese",
    "🍛": "curry rice indian",
    "🍜": "ramen noodle soup japanese",
    "🍝": "spaghetti pasta italian",
    "🍢": "oden japanese",
    "🍣": "sushi japanese",
    "🍤": "fried shrimp tempura japanese",
    "🍥": "fish cake narutomaki japanese",
    "🥮": "moon cake chinese",
    "🥧": "pie dessert",
    "🍦": "ice cream dessert",
    "🍨": "ice cream dessert",
    "🍫": "chocolate dessert",
    "🍬": "candy dessert",
    "🍭": "lollipop candy",
    "🍮": "custard dessert",
    "🍯": "honey sweet",
    "🫖": "teapot tea",
    "🍵": "tea cup",
    "🧃": "juice box drink",
    "🧋": "bubble tea boba",
    "🍶": "sake japanese",
    "🥄": "spoon utensil",
    "🍴": "fork knife utensil",
    "🍽️": "plate utensil",
    "🥙": "shawarma middle eastern",
    "🌯": "burrito mexican",
    "🥗": "salad green",
    "🥘": "paella spanish",
    "🫕": "fondue swiss",
    "🥫": "canned food",
    "🍲": "stew soup",
    "🇨🇽": "christmas island flag",
    "🇨🇨": "cocos islands flag",
    "🇳🇫": "norfolk island flag",
    "🇦🇶": "antarctica flag",
    "🇧🇻": "bouvet island flag",
    "🇭🇲": "heard mcdonald islands flag",
    "😃": "grinning face with big eyes",
    "😄": "grinning face with smiling eyes",
    "😁": "beaming face with smiling eyes",
    "😆": "grinning squinting face",
    "😅": "grinning face with sweat",
    "🤣": "rolling on the floor laughing",
    "🙂": "slightly smiling face",
    "🙃": "upside-down face",
    "😇": "smiling face with halo",
    "🤩": "star-struck",
    "😗": "kissing face",
    "☺️": "smiling face",
    "😚": "kissing face with closed eyes",
    "😙": "kissing face with smiling eyes",
    "🥲": "smiling face with tear",
    "😛": "face with tongue",
    "🤨": "raised eyebrow",
    "😐": "neutral face",
    "😑": "expressionless face",
    "🙄": "face with rolling eyes",
    "😏": "smirking face",
    "😒": "unamused face",
    "🙁": "slightly frowning face",
    "☹️": "frowning face",
    "😔": "pensive face",
    "😪": "sleepy face",
    "😷": "face with medical mask",
    "🤒": "face with thermometer",
    "🤕": "face with head-bandage",
    "🤢": "nauseated face",
    "🤮": "face vomiting",
    "🤧": "sneezing face",
    "🥵": "hot face",
    "🥶": "cold face",
    "😵‍💫": "face with spiral eyes",
    "🤠": "cowboy hat face",
    "🥳": "partying face",
    "🥸": "disguised face",
    "🤓": "nerd face",
    "🧐": "face with monocle",
    "😕": "confused face",
    "😟": "worried face",
    "😯": "hushed face",
    "😲": "astonished face",
    "😳": "flushed face",
    "😦": "frowning face with open mouth",
    "😧": "anguished face",
    "😨": "fearful face",
    "😰": "anxious face with sweat",
    "😥": "sad but relieved face",
    "😱": "face screaming in fear",
    "😖": "confounded face",
    "😣": "persevering face",
    "😞": "disappointed face",
    "😓": "downcast face with sweat",
    "😩": "weary face",
    "😫": "tired face",
    "🥱": "yawning face",
    "😠": "angry face",
    "🤬": "face with symbols on mouth",
    "😈": "devil",
    "👿": "angry devil",
    "💀": "skull",
    "☠️": "skull and crossbones",
    "👻": "ghost",
    "👽": "alien",
    "🤖": "robot",
    "😺": "grinning cat",
    "😸": "grinning cat with smiling eyes",
    "😹": "cat with tears of joy",
    "😻": "smiling cat with heart-eyes",
    "😼": "cat with wry smile",
    "😽": "kissing cat",
    "🙀": "weary cat",
    "😿": "crying cat",
    "😾": "pouting cat",
    "🙈": "see-no-evil monkey",
    "🙉": "hear-no-evil monkey",
    "🙊": "speak-no-evil monkey",
    "🇹🇫": "french southern territories flag"
  };

  // Optimized emoji filtering with memoization
  const filteredEmojis = useMemo(() => {
    if (!searchQuery.trim()) return emojis;

    const query = searchQuery.toLowerCase().trim();
    const queryWords = query.split(' ').filter(word => word.length > 0);

    return emojis.filter(emoji => {
      const emojiName = (emojiNames[emoji] || "").toLowerCase();
      const emojiChar = emoji.toLowerCase();

      // Check if all query words match
      return queryWords.every(word =>
        emojiName.includes(word) ||
        emojiChar.includes(word) ||
        emoji.codePointAt(0).toString(16).includes(word.replace('u+', ''))
      );
    });
  }, [searchQuery]);


  // Memoized Emoji Button Component for better performance
  const EmojiButton = memo(({ emoji, index, onClick }) => (
    <m.button
      className="EmojiButton"
      onClick={() => onClick(emoji)}
      whileHover={{ scale: 1.1 }}
      whileTap={{ scale: 0.95 }}
      initial={{ opacity: 0, scale: 0.8 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{
        duration: 0.2,
        delay: Math.min(index * 0.002, 0.1) // Much faster animation, max 100ms delay
      }}
    >
      {flagMapping[emoji] && flagMapping[emoji] !== null ? (
        <span
          className={flagMapping[emoji]}
          style={{ fontSize: '16px', minWidth: '16px', minHeight: '16px' }}
          title={emoji}
        />
      ) : (
        <span style={{ fontSize: '16px' }} title={emoji}>{emoji}</span>
      )}
    </m.button>
  ));


  if (!isOpen) return null;

  return (
    <m.div
      initial={{ opacity: 0, scale: 0.9, y: 5 }}
      animate={{ opacity: 1, scale: 1, y: 0 }}
      exit={{ opacity: 0, scale: 0.9, y: 5 }}
      transition={{ duration: 0.15, ease: "easeOut" }}
      className="EmojiPicker"
      onClick={(e) => e.stopPropagation()}
    >
      <div className="EmojiPickerHeader">
        <div className="HeaderTop">
          <h3>Pick an emoji</h3>
          <button className="CloseButton" onClick={onClose}>×</button>
        </div>
        <div className="SearchContainer">
          <input
            type="text"
            placeholder="Search emojis..."
            value={searchQuery}
            onChange={handleSearchChange}
            className="EmojiSearchInput"
          />
        </div>
      </div>
      <div className="EmojiGrid">
        {filteredEmojis.length > 0 ? (
          filteredEmojis.map((emoji, index) => (
            <EmojiButton
              key={`${emoji}-${index}`}
              emoji={emoji}
              index={index}
              onClick={handleEmojiClick}
            />
          ))
        ) : (
          <div className="NoEmojisFound">
            <p>No emojis found for "{searchQuery}"</p>
          </div>
        )}
      </div>
    </m.div>
  );
}